development:
  sessions:
    default:
      database: bamboo_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: bamboo_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>